"""
Email Automation Module
Handles secure SMTP email sending with attachments
"""
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path
from typing import List, Dict
from datetime import datetime

class EmailSender:
    """
    Secure email automation with SMTP
    
    Features:
    - Multiple recipients support
    - File attachments (Excel, PDF)
    - HTML email templates
    - Error handling and logging
    - Gmail, Outlook, custom SMTP support
    """
    
    def __init__(self, smtp_host: str, smtp_port: int, sender_email: str, sender_password: str):
        """
        Initialize email sender with SMTP credentials
        
        Args:
            smtp_host: SMTP server hostname
            smtp_port: SMTP server port
            sender_email: Sender email address
            sender_password: Sender email password/app password
        """
        self.smtp_host = smtp_host
        self.smtp_port = smtp_port
        self.sender_email = sender_email
        self.sender_password = sender_password
        
    def create_email_body(self, company_name: str, analysis_summary: str) -> str:
        """
        Create professional HTML email body
        
        Args:
            company_name: Company name
            analysis_summary: Summary text from analysis
            
        Returns:
            HTML email body
        """
        html = f"""
        <html>
        <head>
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    line-height: 1.6;
                    color: #333;
                }}
                .header {{
                    background-color: #1f77b4;
                    color: white;
                    padding: 20px;
                    text-align: center;
                }}
                .content {{
                    padding: 20px;
                    background-color: #f9f9f9;
                }}
                .summary {{
                    background-color: white;
                    padding: 15px;
                    border-left: 4px solid #1f77b4;
                    margin: 20px 0;
                }}
                .footer {{
                    padding: 15px;
                    text-align: center;
                    font-size: 12px;
                    color: #666;
                }}
                pre {{
                    background-color: #f4f4f4;
                    padding: 10px;
                    border-radius: 5px;
                    overflow-x: auto;
                }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>{company_name}</h1>
                <h2>Automated Business Report</h2>
            </div>
            
            <div class="content">
                <p>Dear Team,</p>
                
                <p>Please find attached the automated business intelligence report generated on 
                <strong>{datetime.now().strftime('%B %d, %Y at %I:%M %p')}</strong>.</p>
                
                <div class="summary">
                    <h3>📊 Report Summary</h3>
                    <pre>{analysis_summary}</pre>
                </div>
                
                <p><strong>Attached Files:</strong></p>
                <ul>
                    <li>📊 Excel Report (multi-sheet workbook with detailed analysis)</li>
                    <li>📄 PDF Report (executive summary with visualizations)</li>
                </ul>
                
                <p>This report was automatically generated by the Business Intelligence Automation System.</p>
                
                <p>If you have any questions or need additional analysis, please reply to this email.</p>
                
                <p>Best regards,<br>
                <strong>Analytics Team</strong></p>
            </div>
            
            <div class="footer">
                <p>This is an automated email. Please do not reply directly to this message.</p>
                <p>&copy; {datetime.now().year} {company_name}. All rights reserved.</p>
            </div>
        </body>
        </html>
        """
        return html
    
    def send_email(self, 
                   recipients: List[str], 
                   subject: str, 
                   body: str,
                   attachments: List[str] = None,
                   cc: List[str] = None,
                   bcc: List[str] = None) -> Dict[str, any]:
        """
        Send email with attachments via SMTP
        
        Args:
            recipients: List of recipient email addresses
            subject: Email subject line
            body: HTML email body
            attachments: List of file paths to attach
            cc: Carbon copy recipients
            bcc: Blind carbon copy recipients
            
        Returns:
            Dictionary with success status and message
        """
        try:
            # Create message
            msg = MIMEMultipart()
            msg['From'] = self.sender_email
            msg['To'] = ', '.join(recipients)
            msg['Subject'] = subject
            
            if cc:
                msg['Cc'] = ', '.join(cc)
            
            # Add HTML body
            msg.attach(MIMEText(body, 'html'))
            
            # Attach files
            if attachments:
                for filepath in attachments:
                    file_path = Path(filepath)
                    if file_path.exists():
                        with open(file_path, 'rb') as f:
                            part = MIMEBase('application', 'octet-stream')
                            part.set_payload(f.read())
                            encoders.encode_base64(part)
                            part.add_header(
                                'Content-Disposition',
                                f'attachment; filename= {file_path.name}'
                            )
                            msg.attach(part)
            
            # Combine all recipients
            all_recipients = recipients[:]
            if cc:
                all_recipients.extend(cc)
            if bcc:
                all_recipients.extend(bcc)
            
            # Connect to SMTP server and send
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                server.starttls()  # Enable TLS encryption
                server.login(self.sender_email, self.sender_password)
                server.send_message(msg)
            
            return {
                'success': True,
                'message': f"Email sent successfully to {len(all_recipients)} recipient(s)",
                'recipients': all_recipients,
                'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            }
            
        except smtplib.SMTPAuthenticationError:
            return {
                'success': False,
                'message': "Authentication failed. Check your email and password/app password.",
                'error_type': 'authentication'
            }
        except smtplib.SMTPException as e:
            return {
                'success': False,
                'message': f"SMTP error: {str(e)}",
                'error_type': 'smtp'
            }
        except Exception as e:
            return {
                'success': False,
                'message': f"Unexpected error: {str(e)}",
                'error_type': 'general'
            }
    
    def send_report_email(self,
                         recipients: List[str],
                         company_name: str,
                         analysis_summary: str,
                         report_files: Dict[str, str]) -> Dict[str, any]:
        """
        Send automated report email with standard template
        
        Args:
            recipients: List of recipient emails
            company_name: Company name
            analysis_summary: Analysis summary text
            report_files: Dictionary with 'excel' and 'pdf' file paths
            
        Returns:
            Send result dictionary
        """
        subject = f"{company_name} - Business Report - {datetime.now().strftime('%Y-%m-%d')}"
        body = self.create_email_body(company_name, analysis_summary)
        
        attachments = [
            report_files.get('excel'),
            report_files.get('pdf')
        ]
        attachments = [a for a in attachments if a]  # Remove None values
        
        return self.send_email(
            recipients=recipients,
            subject=subject,
            body=body,
            attachments=attachments
        )
    
    @staticmethod
    def get_smtp_config(provider: str) -> Dict[str, any]:
        """
        Get SMTP configuration for common email providers
        
        Args:
            provider: Email provider name (gmail, outlook, yahoo)
            
        Returns:
            Dictionary with host and port
        """
        configs = {
            'gmail': {'host': 'smtp.gmail.com', 'port': 587},
            'outlook': {'host': 'smtp-mail.outlook.com', 'port': 587},
            'yahoo': {'host': 'smtp.mail.yahoo.com', 'port': 587},
            'office365': {'host': 'smtp.office365.com', 'port': 587}
        }
        
        return configs.get(provider.lower(), {'host': 'smtp.gmail.com', 'port': 587})